project_name: watcher
builds:
  - binary: watcher
    ldflags: 
      - -X github.com/merkely-development/watcher/internal/version.version={{ .Tag }}
      - -X github.com/merkely-development/watcher/internal/version.gitCommit={{ .FullCommit }}
      - -X github.com/merkely-development/watcher/internal/version.gitTreeState=clean
      - -extldflags "-static"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    main: ./cmd/watcher/main.go