project_name: kosli
before:
  hooks:
  - go mod tidy
builds:
  - id: kosli
    binary: kosli
    ldflags: 
      - -w -s
      - -X github.com/kosli-dev/cli/internal/version.version={{ .Tag }}
      - -X github.com/kosli-dev/cli/internal/version.gitCommit={{ .FullCommit }}
      - -X github.com/kosli-dev/cli/internal/version.gitTreeState=clean
      - -extldflags "-static"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      # - linux
      # - windows
    goarch:
      # - amd64
      - arm64
      # - arm
    main: ./cmd/kosli/

archives:
  -
    # Can be used to change the archive formats for specific GOOSs.
    # Most common use case is to archive as zip on Windows.
    # Default is empty.
    format_overrides:
      - goos: windows
        format: zip


brews:
  -
    # GitHub/GitLab repository to push the formula to
    tap:
      owner: kosli-dev
      name: homebrew-tap

      # Optionally a branch can be provided.
      # Defaults to the default repository branch.
      branch: main

    # Template for the url which is determined by the given Token (github, gitlab or gitea)
    #
    # Default depends on the client.
    url_template: "http://https://github.com/kosli-dev/cli/releases/{{ .Tag }}/{{ .ArtifactName }}"

    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Caveats for the user of your binary.
    # Default is empty.
    # caveats: "How to use this binary"

    # Your app's homepage.
    # Default is empty.
    homepage: "https://kosli.com/"

    # Template of your app's description.
    # Default is empty.
    description: "A CLI client for reporting compliance events to  https://kosli.com"

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "MIT"

    # Packages your package depends on.
    dependencies:
      - name: go

    # # So you can `brew test` your formula.
    # # Default is empty.
    # test: |
    #   system "#{bin}/program --version"
    #   ...

    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    install: |
      bin.install "kosli"
      ...