version: '3'

networks:
  cli_net:
    external: true

services:
  registry:
    container_name: cli-registry
    restart: always
    image: registry:2
    ports:
      - 5000:5000

  server:
    networks: [ cli_net ]
    depends_on: [ mongo_rs_initiate ]
    image: ghcr.io/merkely-development/merkely:latest
    container_name: merkely-server
    ports: ["8001:8001"]

  mongo_rs_initiate:
    networks: [ cli_net ]
    image: merkely-mongo-rs
    build:
      context: ./mongo
    container_name: mongo_rs_initiate
    init: true
    depends_on: [ mongo1 ]
    env_file: [ "./mongo/mongo.env" ]
    command: "./mongo/rs_initiate.sh"

  mongo1:
    networks: [ cli_net ]
    hostname: mongo1
    image: merkely-mongo-rs
    build:
      context: ./mongo
    container_name: mongo1
    init: true
    stop_signal: SIGINT
    env_file: [ "./mongo/mongo.env" ]
    tmpfs: [ /tmp, /data/db ]


