version: '3'

networks:
  cli_net:
    external: true

services:
  registry:
    container_name: cli_registry
    restart: always
    image: registry:2
    ports:
      - 5001:5000

  server:
    networks: [ cli_net ]
    depends_on: [ mongo_rs_initiate ]
    image: 772819027869.dkr.ecr.eu-central-1.amazonaws.com/merkely:latest
    env_file: [ "./mongo/mongo.env" ]
    container_name: cli_kosli_server
    ports: ["8001:8001"]

  mongo_rs_initiate:
    networks: [ cli_net ]
    image: kosli-mongo-rs
    build:
      context: ./mongo
    container_name: cli_mongo_rs_initiate
    init: true
    depends_on: [ mongo1 ]
    env_file: [ "./mongo/mongo.env" ]
    command: "/mongo/rs_initiate.sh"

  mongo1:
    networks: [ cli_net ]
    hostname: mongo1
    image: kosli-mongo-rs
    build:
      context: ./mongo
    container_name: mongo1
    init: true
    stop_signal: SIGINT
    env_file: [ "./mongo/mongo.env" ]
    tmpfs: [ /tmp, /data/db ]


