version: '3'

networks:
  cli_net:
    external: true

services:
  registry:
    container_name: cli_registry
    restart: always
    image: registry:2
    ports:
      - 5000:5000

  server:
    networks: [ cli_net ]
    depends_on: [ mongo_rs_initiate ]
    image: ghcr.io/merkely-development/merkely:latest
    container_name: cli_merkely_server
    ports: ["8001:8001"]

  mongo_rs_initiate:
    networks: [ cli_net ]
    image: merkely-mongo-rs
    build:
      context: ./mongo
    container_name: cli_mongo_rs_initiate
    init: true
    depends_on: [ mongo ]
    env_file: [ "./mongo/mongo.env" ]
    command: "./mongo/rs_initiate.sh"

  mongo:
    networks: [ cli_net ]
    hostname: mongo
    image: merkely-mongo-rs
    build:
      context: ./mongo
    container_name: cli_mongo
    init: true
    stop_signal: SIGINT
    env_file: [ "./mongo/mongo.env" ]
    tmpfs: [ /tmp, /data/db ]


