apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "reporter.fullname" . }}
  annotations: {{ toYaml .Values.podAnnotations }}
  labels:
    {{- include "reporter.labels" . | nindent 4 }}

spec:
  schedule: {{ .Values.cronSchedule | quote }}
  jobTemplate:
    spec:
      concurrencyPolicy: Replace
      startingDeadlineSeconds: 30
      template:
        spec:
          serviceAccountName: {{ include "reporter.serviceAccountName" . }}
          containers:
          - name: reporter
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
              - name: MERKELY_API_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: {{ required ".Values.merkelyApiToken.secretName is required." .Values.merkelyApiToken.secretName }}
                    key: {{ .Values.merkelyApiToken.secretKey | default "token" }}
              {{- range $key, $value :=  .Values.env }}
              - name: {{ $key }}
                value: {{ $value }}
              {{ end }}    
            command:
            - /bin/sh
            - -c
            - merkely environment report k8s {{ required ".Values.reporterConfig.merkelyEnvironmentName is required" .Values.reporterConfig.merkelyEnvironmentName }} {{ if .Values.reporterConfig.namespaces }}--namespace {{ .Values.reporterConfig.namespaces | quote }} {{ end }} --owner {{ required ".Values.reporterConfig.merkelyOwner is required" .Values.reporterConfig.merkelyOwner }} {{ if .Values.reporterConfig.dryRun }}--dry-run{{ end }}
            resources:
{{ toYaml .Values.resources | indent 14 }}
          restartPolicy: Never
