[build]
  publish = "public"
  command = "hugo --minify --baseURL $DEPLOY_PRIME_URL"

[build.environment]
  HUGO_VERSION = "0.110.0"
  HUGO_ENABLEGITINFO = "true"


[context.deploy-preview]
  command = "HUGO_BASEURL=$DEPLOY_PRIME_URL hugo --printI18nWarnings --enableGitInfo"

[context.branch-deploy]
  command = "HUGO_BASEURL=$DEPLOY_PRIME_URL hugo --printI18nWarnings --buildDrafts --enableGitInfo"

[[plugins]]
package = "netlify-plugin-checklinks"
  [plugins.inputs]
  skipPatterns = ["https://0-1-36"]