baseURL: 'https://docs.kosli.com'
languageCode: 'en-us'
title: 'Kosli developer documentation'

theme: "book"

markup:
  goldmark:
    extensions:
      typographer: false
  # blackFriday:
  #   smartDashes: false
  # defaultMarkdownHandler: blackFriday

params:
  BookSection: '/'
  BookToC: false