name: Build

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      platforms:
        required: true
        type: string
      AWS_ACCOUNT_ID:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      REGISTRY_ALIAS:
        required: true
        type: string
    secrets:
      slack_channel:
        required: true
      slack_webhook:
        required: true
      ghcr_user:
        required: true
      ghcr_token: 
        required: true         

env:
  IMAGE: ghcr.io/kosli-dev/cli

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: write
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.11'

    # Set up QEMU emulator to allow building multi-arch images
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # This is the a separate action that sets up buildx (buildkit) runner
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.ghcr_user }}
        password: ${{ secrets.ghcr_token }}    

    # Push docker image to public ECR 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/GithubActionsRole
        aws-region: ${{ inputs.AWS_REGION }}
        role-duration-seconds: 2400
        role-session-name: ${{ github.event.repository.name }}

    - name: Login to Amazon ECR public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1.5.0

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.39
        args: --timeout=5m -v

    - name: Run tests
      run: make test_unit

    - name: Build, tag, and push docker image to Amazon ECR Public
      uses: docker/build-push-action@v2
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        REPOSITORY: kosli-reporter
        IMAGE_TAG: ${{ github.sha }}
      with:
        push: true
        tags: "${{ steps.login-ecr-public.outputs.registry }}/${{ inputs.REGISTRY_ALIAS }}/kosli-reporter:${{ inputs.tag }},${{ steps.login-ecr-public.outputs.registry }}/${{ inputs.REGISTRY_ALIAS }}/kosli-reporter:latest,${{ env.IMAGE }}:${{ inputs.tag }}"
        cache-from: type=registry,ref=${{ steps.login-ecr-public.outputs.registry }}/kosli/kosli-reporter:latest
        cache-to: type=inline,mode=max
        build-args: |
          COMMIT_SHA=${{ github.sha }}

    - name: Slack Notification on Failure
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: ${{ secrets.slack_channel }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_TITLE: Build Failed in Client repository
        SLACK_USERNAME: GithubActions
        SLACK_WEBHOOK: ${{ secrets.slack_webhook }}  
       