name: github pages

on:
  push:
    branches:
      - main
    paths:  
      - 'docs.merkely.com/**'
      - '!docs.merkely.com/content/client_reference/**'
      - '!docs.merkely.com/content/helm/**'
  workflow_run:
    workflows: ["helm chart", "release"]
    types:
      - completed
  workflow_dispatch:    

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: cd docs.merkely.com && hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs.merkely.com/public