name: github pages

on:
  push:
    branches:
      - main
    paths:  
      - 'docs.kosli.com/**'
      - '!docs.kosli.com/content/client_reference/**'
      - '!docs.kosli.com/content/helm/**'
  workflow_run:
    workflows: ["helm chart", "release"]
    types:
      - completed
  workflow_dispatch:    

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    
      # - name: link checking
      #   uses: gaurav-nelson/github-action-markdown-link-check@v1
      #   with:
      #     use-quiet-mode: 'yes'
      #     use-verbose-mode: 'yes'
      #     folder-path: 'docs.kosli.com/content/'
      #     config-file: 'link-checker-config.json'  

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: cd docs.kosli.com && hugo --minify

      - name: Check links without using an artifact
        uses: danielfdickinson/link-check-action-hugo-dfd@v0.3
        with:
          canonical-root: "https://docs.kosli.com/"
          upload-logs-as: logs-non-artifact-run
          upload-logs-retention: 1
          use-existing-workspace: "true"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs.kosli.com/public