name: helm chart

on:
  push:
    paths:
      - 'charts/**'

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.0

      - name: Lint
        run: cd charts/k8s-reporter && helm lint .

      - name: Generate Helm Docs
        run: |
          curl -L https://github.com/norwoodj/helm-docs/releases/download/v1.5.0/helm-docs_1.5.0_linux_amd64.deb --output helm-docs.dep
          sudo dpkg -i helm-docs.dep
          rm helm-docs.dep
          cd charts/k8s-reporter 
          helm-docs --template-files README.md.gotmpl,_templates.gotmpl --output-file README.md 
          helm-docs --template-files README.md.gotmpl,_templates.gotmpl --output-file ../../docs.merkely.com/content/docs/helm_chart.md

      - name: Helm Package
        run: helm package charts/k8s-reporter --destination package

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_GCS_CREDENTIALS }}
          export_default_credentials: true
          credentials_file_path: credentials/    

      - name: Pull existing Index.yaml
        run: gsutil cp gs://merkely-charts/index.yaml package/old-index.yaml   

      - name: Helm regenerate repo index
        run: helm repo index package/. --url https://charts.merkely.com/ --merge package/old-index.yaml

      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@v0.4.0
        with:
         path: package
         destination: merkely-charts
         parent: false  

      - name: cleanup
        run: rm -rf package 

      - uses: EndBug/add-and-commit@v7
        with:
          add: '["docs.merkely.com/.", "charts/."]'
          branch: main
          default_author: github_actor
          message: 'Update helm docs'
          pull: 'NO-PULL'     