name: Main

on:
  push:
    branches:
      - '**'


jobs:
  pre-build:
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.prep.outputs.tag }}
    steps:

    - uses: actions/checkout@v2

    - name: Prepare
      id: prep
      run: |
        TAG=$(echo $GITHUB_SHA | head -c7)
        echo "TAG=${TAG}" >> ${GITHUB_ENV}
        echo ::set-output name=tag::${TAG}

  build:
    needs: [pre-build]
    uses: merkely-development/reporter/.github/workflows/build.yml@ce4978f8c9fda273ecedb2ffc20fd80eb537b1e3
    with:
      tag: ${{ needs.pre-build.outputs.tag }}
      platforms: linux/amd64
    secrets:
      slack_webhook: ${{ secrets.MERKELY_SLACK_CI_FAILURES_WEBHOOK }}
      slack_channel: ${{ secrets.MERKELY_SLACK_CI_FAILURES_CHANNEL }} 