name: publish docs

on:
  push:
    branches:
      - new-syntax
    paths:  
      - 'docs.kosli.com/**'
      - '!docs.kosli.com/content/client_reference/**'
      - '!docs.kosli.com/content/helm/**'
  # workflow_run:
  #   workflows: ["helm chart", "release"]
  #   types:
  #     - completed
  workflow_dispatch:    

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Generate docs
        run: |
          make docs

      # Deploy to local repo
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docs-staging
          FOLDER: docs.kosli.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}