name: publish docs

on:
  push:
    branches:
      - main
    paths:  
      - 'docs.kosli.com/**'
      - '!docs.kosli.com/content/client_reference/**'
      - '!docs.kosli.com/content/helm/**'
  workflow_dispatch:    

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      # Deploy to local repo
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docs-main
          FOLDER: docs.kosli.com
          TARGET_DIR: docs.kosli.com
          CLEAR_GLOBS_FILE: ".clear-files"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "From: {msg}"
