name: release

on:
  push:
    tags:        
      - 'v*' 

env: 
  GO_VERSION: 1.16.4

jobs:
  pre-build:
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
    
    - uses: actions/checkout@v2

    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1

  build:
    needs: [pre-build]
    uses: merkely-development/reporter/.github/workflows/build.yml@ed92340169ea9601333135afb9895eec66fb223e
    with:
      tag: ${{ needs.pre-build.outputs.tag }}
      platforms: linux/amd64,linux/arm64
    secrets:
      slack_webhook: ${{ secrets.MERKELY_SLACK_CI_FAILURES_WEBHOOK }}
      slack_channel: ${{ secrets.MERKELY_SLACK_CI_FAILURES_CHANNEL }}

  goreleaser:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs-gen:
    needs: [goreleaser]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Generate docs
        run: |
          make docs

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'docs.merkely.com/.'
          branch: main
          default_author: github_actor
          message: 'Update docs'
          pull_strategy: 'NO-PULL'
