name: ci-upload-lambda-layer

on:
  push:
    branches:
      - 'ci-upload-lambda-layer'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pre-build:
    runs-on: ubuntu-20.04
    outputs:
      layer-version: ${{ steps.tag.outputs.tag }}
    steps:

    - uses: actions/checkout@v3

    # - name: Get tag
    #   id: tag
    #   uses: dawidd6/action-get-tag@v1

  upload-lambda-layer:
    needs: [pre-build]
    # uses: kosli-dev/cli/.github/workflows/upload-lambda-layer.yml@main
    uses: kosli-dev/cli/.github/workflows/upload-lambda-layer.yml@ci-upload-lambda-layer
    with:
      # tag: ${{ needs.pre-build.outputs.tag }}
      tag: v2.4.1
      OIDC_ROLE_ARN: arn:aws:iam::772819027869:role/cli
      AWS_REGION: eu-central-1

  update-evidence-reporters:
    runs-on: ubuntu-20.04
    needs: [upload-lambda-layer]
    steps:
      # - run: echo ${{ needs.upload-lambda-layer.outputs.layer_version_arn }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.KOSLI_REPORTER_REPO_ACCESS_TOKEN }}
          repository: kosli-dev/terraform-evidence-reporter
          event-type: deploy-evidence-reporter
          client-payload: '{"layer_version_arn_kosli_bin": "${{ needs.upload-lambda-layer.outputs.layer_version_arn }}"}'
