name: Upload lambda layer to AWS

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      OIDC_ROLE_ARN:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string

jobs:
  upload:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: '1.20.2'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ inputs.OIDC_ROLE_ARN }}
        aws-region: ${{ inputs.AWS_REGION }}
        role-duration-seconds: 900
        role-session-name: ${{ github.event.repository.name }}
        mask-aws-account-id: false

    # Upload lambda layer and make i–µ publicly accessible
    - name: Upload Kosli bin Lambda layer
      id: upload-lambda-layer
      env:
        TAG: ${{ inputs.tag }}
        LAYER_NAME: kosli-cli-test
        ZIP_FILE_NAME: kosli_lambda_layer.zip
      run: |
        make build
        mv kosli bin/
        zip -r $ZIP_FILE_NAME bin/kosli
        AWS_REGIONS=(
            "us-west-1"
            "us-west-2"
            "us-east-1"
            "us-east-2"
            "ca-central-1" 
            "eu-central-1"
            "eu-north-1"
            "eu-west-1"
            "eu-west-2"
            "eu-west-3"
        )
        for region in "${AWS_REGIONS[@]}"; do
            echo "Publishing layer to $region..."

            LAYER_VERSION_NUMBER=$(aws lambda publish-layer-version \
                --region $region \
                --zip-file fileb://$ZIP_FILE_NAME \
                --layer-name $LAYER_NAME \
                --compatible-architectures x86_64 \
                --description '{"kolsi_cli_version": "${{ inputs.tag }}"}' \
                | jq .Version)
            aws lambda add-layer-version-permission \
                --region $region \
                --layer-name $LAYER_NAME \
                --statement-id public \
                --version-number $LAYER_VERSION_NUMBER \
                --principal '*' \
                --action lambda:GetLayerVersion \
                --output json
            echo "Published lambda layer version $LAYER_VERSION_NUMBER, $region complete"
            echo ""
        done